# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' NoiseEstimationFFTCosWin.
#' 
#' Estimate the noise of a spectrum using a FFT filter and a cosinus window in frequency domain.
#' 
#' @param x an Rcpp::NumericVector containing the spectrum intensities.
#' @param filWinSize an integer specified the cosinus win size in samples.
#' 
#' @return an Rcpp::NumericVector containing the estimated noise.
#' @export
NoiseEstimationFFTCosWin <- function(x, filWinSize = 40L) {
    .Call('rMSIproc_NoiseEstimationFFTCosWin', PACKAGE = 'rMSIproc', x, filWinSize)
}

#' NoiseEstimationFFTExpWin.
#' 
#' Estimate the noise of a spectrum using a FFT filter and a decay exponential window in frequency domain.
#' 
#' @param x an Rcpp::NumericVector containing the spectrum intensities.
#' @param filWinSize an integer specified the cosinus win size in samples.
#' 
#' @return an Rcpp::NumericVector containing the estimated noise.
#' @export
NoiseEstimationFFTExpWin <- function(x, filWinSize = 40L) {
    .Call('rMSIproc_NoiseEstimationFFTExpWin', PACKAGE = 'rMSIproc', x, filWinSize)
}

#' NoiseEstimationFFTCosWinMat.
#' 
#' Estimate the noise of some spectra using a FFT filter and a cosinus window in frequency domain.
#' 
#' @param x an Rcpp::NumericMatrix containing the spectra intensities. Each spectrum in a row.
#' @param filWinSize an integer specified the cosinus win size in samples.
#' 
#' @return an Rcpp::NumericMatrix containing the estimated noise in a matrix where each spectrum is a row.
#' @export
NoiseEstimationFFTCosWinMat <- function(x, filWinSize = 40L) {
    .Call('rMSIproc_NoiseEstimationFFTCosWinMat', PACKAGE = 'rMSIproc', x, filWinSize)
}

#' NoiseEstimationFFTExpWinMat.
#' 
#' Estimate the noise of some spectra using a FFT filter and a decay exponential window in frequency domain.
#' 
#' @param x an Rcpp::NumericMatrix containing the spectra intensities. Each spectrum in a row.
#' @param filWinSize an integer specified the cosinus win size in samples.
#' 
#' @return a
NoiseEstimationFFTExpWinMat <- function(x, filWinSize = 40L) {
    .Call('rMSIproc_NoiseEstimationFFTExpWinMat', PACKAGE = 'rMSIproc', x, filWinSize)
}

FullImageProcess <- function(basePath, fileNames, mass, refSpectrum, numRows, dataType, numOfThreads, runAlignment = FALSE, SNR = 5, WinSize = 10L, InterpolationUpSampling = 10L, SmoothingKernelSize = 5L, binningTolerance = 0.05, binningFilter = 0.9) {
    .Call('rMSIproc_FullImageProcess', PACKAGE = 'rMSIproc', basePath, fileNames, mass, refSpectrum, numRows, dataType, numOfThreads, runAlignment, SNR, WinSize, InterpolationUpSampling, SmoothingKernelSize, binningTolerance, binningFilter)
}

#' DetectPeaks_C.
#' 
#' Detect peaks from a Rcpp::NumericVector object and returns data in a R matrix.
#' This method is only exported to be use by R function DetectPeaks which is an actual R function.
#' The returned peak positions follows C indexing style, this is starts with zero.
#' 
#' @param mass a NumericVector containing the mass axis of the spectrum.
#' @param intensity a NumericVector where peaks must be detected.
#' @param SNR Only peaks with an equal or higher SNR are retained.
#' @param WinSize The windows used to detect peaks and caculate noise.
#' 
#' @return a NumerixMatrix of 3 rows corresponding to: mass, intensity of the peak and SNR.
#' 
DetectPeaks_C <- function(mass, intensity, SNR = 5, WinSize = 20L) {
    .Call('rMSIproc_DetectPeaks_C', PACKAGE = 'rMSIproc', mass, intensity, SNR, WinSize)
}

PrintrMSIObjectInfo <- function(basePath, fileNames, massChannels, numRows, dataType) {
    invisible(.Call('rMSIproc_PrintrMSIObjectInfo', PACKAGE = 'rMSIproc', basePath, fileNames, massChannels, numRows, dataType))
}

LoadrMSIDataCube <- function(basePath, fileNames, massChannels, numRows, dataType, cubeSel) {
    .Call('rMSIproc_LoadrMSIDataCube', PACKAGE = 'rMSIproc', basePath, fileNames, massChannels, numRows, dataType, cubeSel)
}

#' Smoothing_SavitzkyGolay.
#' 
#' Computes the Savitzky-Golay smoothing of a vector x using a filter size of sgSize.
#' @param x the data vector to smooth.
#' @param sgSize valid values are: 5, 7, 9 and 11.
#' @return the smoothed data vector.
Smoothing_SavitzkyGolay <- function(x, sgSize = 5L) {
    .Call('rMSIproc_Smoothing_SavitzkyGolay', PACKAGE = 'rMSIproc', x, sgSize)
}

